---
- name: Deploy Homelab Observability Stack
  hosts: all
  become: yes
  tasks:
    - name: Ensure git, podman, and podman-compose are installed
      apt:
        name:
          - git
          - podman
          - podman-compose
        state: present
        update_cache: yes

    - name: Pull the latest code from GitHub
      git:
        repo: 'https://github.com/DonatSzabo/Homelab-Resource-monitor.git'
        dest: '/opt/homelab-api'
        version: main
        force: yes

    - name: Tear down the old containers (if they exist)
      command: podman-compose down
      args:
        chdir: /opt/homelab-api
      ignore_errors: yes

    - name: Build and spin up the new 3-tier stack
      command: podman-compose up -d --build
      args:
        chdir: /opt/homelab-api
